// Pinned BLS byte vectors for seed=1, Domain::Vote, msg = b"azbft-bls-test-vector-v1".
// min-pk: PK_SEED1 = 48-byte G1 compressed, SIG_SEED1 = 96-byte G2 compressed.
// Generated by the pinned Rust toolchain and `blst` dependency using the
// `print_known_seed_vectors` helper test. These are not security-sensitive (a
// public key and a signature for a throwaway seed); they exist only to catch a
// cross-platform / library-version encoding regression .
const PK_SEED1: [u8; BLS_PUBLIC_KEY_LEN] = [
    144, 223, 236, 4, 162, 91, 204, 215, 248, 202, 164, 23, 19, 148, 233, 187, 208, 68, 90, 43, 24,
    132, 247, 119, 147, 5, 224, 205, 2, 126, 214, 60, 21, 20, 160, 9, 96, 141, 32, 119, 241, 73,
    237, 139, 129, 251, 59, 223,
];
const SIG_SEED1: [u8; BLS_SIGNATURE_LEN] = [
    177, 32, 177, 102, 101, 185, 160, 93, 170, 158, 182, 40, 240, 234, 154, 247, 52, 227, 172,
    234, 168, 116, 181, 118, 39, 38, 131, 208, 206, 8, 19, 50, 112, 0, 43, 50, 134, 63, 108,
    92, 125, 67, 238, 155, 126, 42, 164, 87, 10, 136, 115, 178, 108, 135, 53, 130, 63, 152,
    152, 190, 136, 246, 84, 112, 215, 37, 34, 66, 25, 0, 30, 113, 194, 188, 113, 195, 177,
    87, 196, 238, 200, 49, 29, 221, 196, 144, 116, 214, 151, 190, 178, 107, 213, 160, 132,
    159,
];

/// Prints the seed-1 vectors so they can be pinned above. Run with
/// `--nocapture`. Ignored by default.
#[test]
#[ignore = "prints byte vectors for pinning; run with --nocapture"]
fn print_known_seed_vectors() {
    let sk = BlsSecretKey::from_seed(1);
    let pk = sk.public().to_bytes();
    let sig = sk.sign(Domain::Vote, b"azbft-bls-test-vector-v1").to_bytes();
    println!("PK_SEED1 = {:?};", pk);
    println!("SIG_SEED1 = {:?};", sig);
}
