[package]
name = "azbft-devnet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
azbft-core = { path = "../azbft-core" }
azbft-crypto = { path = "../azbft-crypto", features = ["insecure-test-keys"] }
azbft-types = { path = "../azbft-types" }
borsh.workspace = true
blake3.workspace = true
rand_chacha = "0.3"
rand_core.workspace = true
thiserror.workspace = true
